docs(): add image repo docs
matrixone-cloud/observability-charts pull request #5
Opened 2024-01-31 03:25 UTC by EZ4BRUCE

## What type of PR is this?

* [ ] Feature
* [ ] BUG
* [ ] Alerts
* [ ] Improvement
* [ ] Documentation
* [ ] Test and CI

## Which issue(s) this PR related:

issue #

## What this PR does / why we need it:

在 private chart 的 values.yaml 中添加镜像仓库修改的注释

2024-01-31 03:47 UTC, xzxiong requested changes
no need  to change chart.version
最后再mo-ctl 1.2.0 只release 一次。

2024-01-31 04:17 UTC, EZ4BRUCE commented
> no need to change chart.version 最后再mo-ctl 1.2.0 只release 一次。

done

2024-02-02 08:25 UTC, xzxiong approved these changes

2024-02-02 08:25 UTC, xzxiong commented on charts/mo-ob-private/values.yaml
> +    #   repository: "registry.cn-hangzhou.aliyuncs.com/ack-cos/grafana"
缺了 sidecar

2024-02-04 08:15 UTC, merged